### ISSUE TITLE
What does the gatsby-config look like?

### ISSUE THREAD

**Issue by LinnJS** [c0b41/gatsby-plugin-onesignal#2]
I would love to use this plugin but there is no readme on how to use it. What might be an example of the `gatsby-config`? I am sure it has to take some kind of options for the API key right? Would not mind opening a PR to add a readme if you don't mind supplying the example.

**Comment by c0b41** [comment]
example config 

```
{
    resolve: `@c0b41/gatsby-plugin-onesignal`,
    options: {
      appid: 'xxxx-xxx-xxx-xx-xxx'
    }
}
```
